//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekSchedule.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceRules
    {
        public int Id { get; set; }
        public int ProfessorId { get; set; }
        public int DayOfWeek { get; set; }
        public int ClassNumber { get; set; }
    
        public virtual Professor Professor { get; set; }
    }
}
