//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekClassSchedule.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public Classroom()
        {
            this.ClassroomClasses = new HashSet<ClassroomClasses>();
            this.WeekSchedule = new HashSet<WeekSchedule>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long NumberOfClasses { get; set; }
    
        public virtual ICollection<ClassroomClasses> ClassroomClasses { get; set; }
        public virtual ICollection<WeekSchedule> WeekSchedule { get; set; }
    }
}
