//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekClassSchedule.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        public Professor()
        {
            this.AttendanceRules = new HashSet<AttendanceRules>();
            this.WeekSchedule = new HashSet<WeekSchedule>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public long NumberOfClassesWeek { get; set; }
        public long NumberOfRemainingClasses { get; set; }
    
        public virtual ICollection<AttendanceRules> AttendanceRules { get; set; }
        public virtual ICollection<WeekSchedule> WeekSchedule { get; set; }
    }
}
