//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekClassSchedule.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vWeeklyScheduleByClass
    {
        public long ClassroomId { get; set; }
        public long ClassNumber { get; set; }
        public long Monday { get; set; }
        public long Tuesday { get; set; }
        public long Wednesday { get; set; }
        public long Thursday { get; set; }
        public long Friday { get; set; }
    }
}
