//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekClassSchedule.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vWeeklyScheduleByClass
    {
        public int Classe { get; set; }
        public int Aula { get; set; }
        public Nullable<int> Segunda { get; set; }
        public Nullable<int> Terça { get; set; }
        public Nullable<int> Quarta { get; set; }
        public Nullable<int> Quinta { get; set; }
        public Nullable<int> Sexta { get; set; }
    }
}
