//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekClassSchedule.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeekClassScheduleEntities : DbContext
    {
        public WeekClassScheduleEntities()
            : base("name=WeekClassScheduleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AttendanceRules> AttendanceRules { get; set; }
        public DbSet<Classroom> Classroom { get; set; }
        public DbSet<ClassroomClasses> ClassroomClasses { get; set; }
        public DbSet<Professor> Professor { get; set; }
        public DbSet<vWeeklyScheduleByClass> vWeeklyScheduleByClass { get; set; }
        public DbSet<WeekSchedule> WeekSchedule { get; set; }
    }
}
