//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekSchedule.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekSchedule2
    {
        public short ClassroomId { get; set; }
        public short ClassNumber { get; set; }
        public short WeekDay { get; set; }
        public int ProfessorId { get; set; }
    }
}
