//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekSchedule.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyClassSchedule
    {
        public int Id { get; set; }
        public int ClassroomId { get; set; }
        public int ClassNumber { get; set; }
        public Nullable<int> MondayProfessorId { get; set; }
        public Nullable<int> TuesdayProfessorId { get; set; }
        public Nullable<int> WednesdayProfessorId { get; set; }
        public Nullable<int> ThursdayProfessorId { get; set; }
        public Nullable<int> FridayProfessorId { get; set; }
    }
}
